export { default as FileText } from './file-text';
export { default as Download } from './download';
export { default as LoaderCircle } from './loader-circle';
export { default as Briefcase } from './briefcase';
export { default as User } from "./user"
export { default as GraduationCap } from "./graduation-cap"
export { default as Eye } from "./eye"
export { default as Mail } from "./mail"
export { default as Phone } from "./phone"
export { default as Github } from "./github"
export { default as Linkedin } from "./linkedin"
export { default as Twitter } from "./twitter"
export { default as Instagram } from "./instagram"
export { default as MapPin } from "./map-pin"
